import 'package:flutter/material.dart';

class Constants {
  static const NAME_APP = 'Architecture';
  static const LOGO_APP = 'assets/images/logo.png';

  static const IDENTITY = 'https://identityapptest.herokuapp.com/api';
  //static const IDENTITY = 'http://172.17.64.1:4000/api';
  static const BASE_URL = 'sad54as5d4as4d54a';

  static const FULL_SCREEN_PADDING = 10.0;
  static const COUTRY_LIST_ISO = [
    {"code": "+93", "name": "Afghanistan", "iso": "AF"},
    {"code": "+355", "name": "Albania", "iso": "AL"},
    {"code": "+213", "name": "Algeria", "iso": "DZ"},
    {"code": "+1 684", "name": "American Samoa", "iso": "AS"},
    {"code": "+376", "name": "Andorra", "iso": "AD"},
    {"code": "+244", "name": "Angola", "iso": "AO"},
    {"code": "+1 264", "name": "Anguilla", "iso": "AI"},
    {"code": "+1 268", "name": "Antigua and Barbuda", "iso": "AG"},
    {"code": "+54", "name": "Argentina", "iso": "AR"},
    {"code": "+374", "name": "Armenia", "iso": "AM"},
    {"code": "+297", "name": "Aruba", "iso": "AW"},
    {"code": "+61", "name": "Australia", "iso": "AU"},
    {"code": "+43", "name": "Austria", "iso": "AT"},
    {"code": "+994", "name": "Azerbaijan", "iso": "AZ"},
    {"code": "+973", "name": "Bahrain", "iso": "BH"},
    {"code": "+880", "name": "Bangladesh", "iso": "BD"},
    {"code": "+1 246", "name": "Barbados", "iso": "BB"},
    {"code": "+375", "name": "Belarus", "iso": "BY"},
    {"code": "+32", "name": "Belgium", "iso": "BE"},
    {"code": "+501", "name": "Belize", "iso": "BZ"},
    {"code": "+229", "name": "Benin", "iso": "BJ"},
    {"code": "+1 441", "name": "Bermuda", "iso": "BM"},
    {"code": "+975", "name": "Bhutan", "iso": "BT"},
    {"code": "+387", "name": "Bosnia and Herzegovina", "iso": "BA"},
    {"code": "+267", "name": "Botswana", "iso": "BW"},
    {"code": "+55", "name": "Brazil", "iso": "BR"},
    {"code": "+359", "name": "Bulgaria", "iso": "BG"},
    {"code": "+226", "name": "Burkina Faso", "iso": "BF"},
    {"code": "+257", "name": "Burundi", "iso": "BI"},
    {"code": "+855", "name": "Cambodia", "iso": "KH"},
    {"code": "+237", "name": "Cameroon", "iso": "CM"},
    {"code": "+1", "name": "Canada", "iso": "CA"},
    {"code": "+235", "name": "Chad", "iso": "TD"},
    {"code": "+56", "name": "Chile", "iso": "CL"},
    {"code": "+86", "name": "China", "iso": "CN"},
    {"code": "+61", "name": "Christmas Island", "iso": "CX"},
    {"code": "+57", "name": "Colombia", "iso": "CO"},
    {"code": "+506", "name": "Costa Rica", "iso": "CR"},
    {"code": "+385", "name": "Croatia", "iso": "HR"},
    {"code": "+53", "name": "Cuba", "iso": "CU"},
    {"code": "+537", "name": "Cyprus", "iso": "CY"},
    {"code": "+45", "name": "Denmark", "iso": "DK"},
    {"code": "+253", "name": "Djibouti", "iso": "DJ"},
    {"code": "+1 767", "name": "Dominica", "iso": "DM"},
    {"code": "+593", "name": "Ecuador", "iso": "EC"},
    {"code": "+20", "name": "Egypt", "iso": "EG"},
    {"code": "+503", "name": "El Salvador", "iso": "SV"},
    {"code": "+240", "name": "Equatorial Guinea", "iso": "GQ"},
    {"code": "+291", "name": "Eritrea", "iso": "ER"},
    {"code": "+372", "name": "Estonia", "iso": "EE"},
    {"code": "+251", "name": "Ethiopia", "iso": "ET"},
    {"code": "+679", "name": "Fiji", "iso": "FJ"},
    {"code": "+358", "name": "Finland", "iso": "FI"},
    {"code": "+33", "name": "France", "iso": "FR"},
    {"code": "+594", "name": "French Guiana", "iso": "GF"},
    {"code": "+689", "name": "French Polynesia", "iso": "PF"},
    {"code": "+241", "name": "Gabon", "iso": "GA"},
    {"code": "+995", "name": "Georgia", "iso": "GE"},
    {"code": "+49", "name": "Germany", "iso": "DE"},
    {"code": "+233", "name": "Ghana", "iso": "GH"},
    {"code": "+350", "name": "Gibraltar", "iso": "GI"},
    {"code": "+30", "name": "Greece", "iso": "GR"},
    {"code": "+299", "name": "Greenland", "iso": "GL"},
    {"code": "+1 473", "name": "Grenada", "iso": "GD"},
    {"code": "+590", "name": "Guadeloupe", "iso": "GP"},
    {"code": "+1 671", "name": "Guam", "iso": "GU"},
    {"code": "+502", "name": "Guatemala", "iso": "GT"},
    {"code": "+224", "name": "Guinea", "iso": "GN"},
    {"code": "+245", "name": "Guinea-Bissau", "iso": "GW"},
    {"code": "+595", "name": "Guyana", "iso": "GY"},
    {"code": "+509", "name": "Haiti", "iso": "HT"},
    {"code": "+504", "name": "Honduras", "iso": "HN"},
    {"code": "+36", "name": "Hungary", "iso": "HU"},
    {"code": "+354", "name": "Iceland", "iso": "IS"},
    {"code": "+91", "name": "India", "iso": "IN"},
    {"code": "+62", "name": "Indonesia", "iso": "ID"},
    {"code": "+964", "name": "Iraq", "iso": "IQ"},
    {"code": "+353", "name": "Ireland", "iso": "IE"},
    {"code": "+972", "name": "Israel", "iso": "IL"},
    {"code": "+39", "name": "Italy", "iso": "IT"},
    {"code": "+1 876", "name": "Jamaica", "iso": "JM"},
    {"code": "+81", "name": "Japan", "iso": "JP"},
    {"code": "+962", "name": "Jordan", "iso": "JO"},
    {"code": "+7 7", "name": "Kazakhstan", "iso": "KZ"},
    {"code": "+254", "name": "Kenya", "iso": "KE"},
    {"code": "+686", "name": "Kiribati", "iso": "KI"},
    {"code": "+965", "name": "Kuwait", "iso": "KW"},
    {"code": "+996", "name": "Kyrgyzstan", "iso": "KG"},
    {"code": "+371", "name": "Latvia", "iso": "LV"},
    {"code": "+961", "name": "Lebanon", "iso": "LB"},
    {"code": "+266", "name": "Lesotho", "iso": "LS"},
    {"code": "+231", "name": "Liberia", "iso": "LR"},
    {"code": "+218", "name": "Libya", "iso": "LY"},
    {"code": "+423", "name": "Liechtenstein", "iso": "LI"},
    {"code": "+370", "name": "Lithuania", "iso": "LT"},
    {"code": "+352", "name": "Luxembourg", "iso": "LU"},
    {"code": "+261", "name": "Madagascar", "iso": "MG"},
    {"code": "+265", "name": "Malawi", "iso": "MW"},
    {"code": "+60", "name": "Malaysia", "iso": "MY"},
    {"code": "+960", "name": "Maldives", "iso": "MV"},
    {"code": "+223", "name": "Mali", "iso": "ML"},
    {"code": "+356", "name": "Malta", "iso": "MT"},
    {"code": "+596", "name": "Martinique", "iso": "MQ"},
    {"code": "+222", "name": "Mauritania", "iso": "MR"},
    {"code": "+230", "name": "Mauritius", "iso": "MU"},
    {"code": "+262", "name": "Mayotte", "iso": "YT"},
    {"code": "+52", "name": "Mexico", "iso": "MX"},
    {"code": "+377", "name": "Monaco", "iso": "MC"},
    {"code": "+976", "name": "Mongolia", "iso": "MN"},
    {"code": "+382", "name": "Montenegro", "iso": "ME"},
    {"code": "+1664", "name": "Montserrat", "iso": "MS"},
    {"code": "+212", "name": "Morocco", "iso": "MA"},
    {"code": "+95", "name": "Myanmar", "iso": "MM"},
    {"code": "+264", "name": "Namibia", "iso": "NA"},
    {"code": "+674", "name": "Nauru", "iso": "NR"},
    {"code": "+977", "name": "Nepal", "iso": "NP"},
    {"code": "+687", "name": "New Caledonia", "iso": "NC"},
    {"code": "+64", "name": "New Zealand", "iso": "NZ"},
    {"code": "+505", "name": "Nicaragua", "iso": "NI"},
    {"code": "+234", "name": "Nigeria", "iso": "NG"},
    {"code": "+683", "name": "Niue", "iso": "NU"},
    {"code": "+672", "name": "Norfolk Island", "iso": "NF"},
    {"code": "+47", "name": "Norway", "iso": "NO"},
    {"code": "+968", "name": "Oman", "iso": "OM"},
    {"code": "+92", "name": "Pakistan", "iso": "PK"},
    {"code": "+680", "name": "Palau", "iso": "PW"},
    {"code": "+507", "name": "Panama", "iso": "PA"},
    {"code": "+675", "name": "Papua New Guinea", "iso": "PG"},
    {"code": "+595", "name": "Paraguay", "iso": "PY"},
    {"code": "+51", "name": "Peru", "iso": "PE"},
    {"code": "+48", "name": "Poland", "iso": "PL"},
    {"code": "+351", "name": "Portugal", "iso": "PT"},
    {"code": "+1 787", "name": "Puerto Rico", "iso": "PR"},
    {"code": "+974", "name": "Qatar", "iso": "QA"},
    {"code": "+40", "name": "Romania", "iso": "RO"},
    {"code": "+250", "name": "Rwanda", "iso": "RW"},
    {"code": "+685", "name": "Samoa", "iso": "WS"},
    {"code": "+378", "name": "San Marino", "iso": "SM"},
    {"code": "+966", "name": "Saudi Arabia", "iso": "SA"},
    {"code": "+221", "name": "Senegal", "iso": "SN"},
    {"code": "+381", "name": "Serbia", "iso": "RS"},
    {"code": "+248", "name": "Seychelles", "iso": "SC"},
    {"code": "+232", "name": "Sierra Leone", "iso": "SL"},
    {"code": "+65", "name": "Singapore", "iso": "SG"},
    {"code": "+421", "name": "Slovakia", "iso": "SK"},
    {"code": "+386", "name": "Slovenia", "iso": "SI"},
    {"code": "+677", "name": "Solomon Islands", "iso": "SB"},
    {"code": "+27", "name": "South Africa", "iso": "ZA"},
    {
      "code": "+500",
      "name": "South Georgia and the South Sandwich Islands",
      "iso": "GS"
    },
    {"code": "+34", "name": "Spain", "iso": "ES"},
    {"code": "+94", "name": "Sri Lanka", "iso": "LK"},
    {"code": "+597", "name": "Suriname", "iso": "SR"},
    {"code": "+46", "name": "Sweden", "iso": "SE"},
    {"code": "+41", "name": "Switzerland", "iso": "CH"},
    {"code": "+886", "name": "Taiwan", "iso": "TW"},
    {"code": "+992", "name": "Tajikistan", "iso": "TJ"},
    {"code": "+66", "name": "Thailand", "iso": "TH"},
    {"code": "+228", "name": "Togo", "iso": "TG"},
    {"code": "+690", "name": "Tokelau", "iso": "TK"},
    {"code": "+676", "name": "Tonga", "iso": "TO"},
    {"code": "+1 868", "name": "Trinidad and Tobago", "iso": "TT"},
    {"code": "+216", "name": "Tunisia", "iso": "TN"},
    {"code": "+90", "name": "Turkey", "iso": "TR"},
    {"code": "+993", "name": "Turkmenistan", "iso": "TM"},
    {"code": "+688", "name": "Tuvalu", "iso": "TV"},
    {"code": "+256", "name": "Uganda", "iso": "UG"},
    {"code": "+380", "name": "Ukraine", "iso": "UA"},
    {"code": "+598", "name": "Uruguay", "iso": "UY"},
    {"code": "+998", "name": "Uzbekistan", "iso": "UZ"},
    {"code": "+678", "name": "Vanuatu", "iso": "VU"},
    {"code": "+681", "name": "Wallis and Futuna", "iso": "WF"},
    {"code": "+967", "name": "Yemen", "iso": "YE"},
    {"code": "+260", "name": "Zambia", "iso": "ZM"},
    {"code": "+263", "name": "Zimbabwe", "iso": "ZW"}
  ];
}
